name: Generate and Push Tag

on:
  push:
    branches:
      - main # Trigger on push to the main branch, adjust as needed

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get the latest tag
        id: get-latest-tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          echo "::set-output name=latest-tag::$LATEST_TAG"

      - name: Calculate new version
        id: calc-new-version
        run: |
          LATEST_TAG=${{ steps.get-latest-tag.outputs.latest-tag }}
          echo "Latest tag is $LATEST_TAG"

          # Extract the major, minor, and patch parts of the version
          VERSION_REGEX="^v([0-9]+)\.([0-9]+)\.([0-9]+)$"
          if [[ $LATEST_TAG =~ $VERSION_REGEX ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
          else
            MAJOR=0
            MINOR=0
            PATCH=0
          fi

          # Increment the minor version
          MINOR=$((MINOR + 1))

          # Create new tag
          NEW_TAG="v${MAJOR}.${MINOR}.0"
          echo "New tag will be $NEW_TAG"
          echo "::set-output name=new-tag::$NEW_TAG"

      - name: Create and push tag
        env:
          NEW_TAG: ${{ steps.calc-new-version.outputs.new-tag }}
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
